-- MySQL Script generated by MySQL Workbench
-- Wed Dec 23 00:08:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hryniewickij
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hryniewickij
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hryniewickij` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hryniewickij` ;

-- -----------------------------------------------------
-- Table `hryniewickij`.`Klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Klient` (
  `idKlienta` INT NOT NULL AUTO_INCREMENT,
  `Forma_Prawna` ENUM('ind', 'biz') NOT NULL,
  `Tel_Kontaktowy` VARCHAR(20) NOT NULL,
  `Adres_Email` VARCHAR(45) NULL DEFAULT NULL,
  `PESEL` VARCHAR(45) NULL DEFAULT NULL,
  `NIP` VARCHAR(45) NULL DEFAULT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKlienta`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Faktury`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Faktury` (
  `idFaktury` INT NOT NULL AUTO_INCREMENT,
  `kwota` DECIMAL(10,2) NOT NULL,
  `nabywca` INT NOT NULL,
  PRIMARY KEY (`idFaktury`),
  INDEX `nabywca` (`nabywca` ASC) VISIBLE,
  CONSTRAINT `Faktury_ibfk_1`
    FOREIGN KEY (`nabywca`)
    REFERENCES `hryniewickij`.`Klient` (`idKlienta`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Kategorie` (
  `idKategorii` INT NOT NULL AUTO_INCREMENT,
  `Nazwa_Kategorii` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKategorii`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Wyposazenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Wyposazenie` (
  `idWyposazenia` INT NOT NULL AUTO_INCREMENT,
  `Kategoria` INT NOT NULL,
  `Nazwa` VARCHAR(45) NOT NULL,
  `cena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idWyposazenia`),
  INDEX `Kategoria` (`Kategoria` ASC) VISIBLE,
  CONSTRAINT `Wyposazenie_ibfk_1`
    FOREIGN KEY (`Kategoria`)
    REFERENCES `hryniewickij`.`Kategorie` (`idKategorii`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Magazyn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Magazyn` (
  `Przedmiot` INT NOT NULL,
  `ilosc` INT NOT NULL,
  PRIMARY KEY (`Przedmiot`),
  CONSTRAINT `Magazyn_ibfk_1`
    FOREIGN KEY (`Przedmiot`)
    REFERENCES `hryniewickij`.`Wyposazenie` (`idWyposazenia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Typ_Pojazdu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Typ_Pojazdu` (
  `idTypu` INT NOT NULL AUTO_INCREMENT,
  `Typ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypu`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Pojazd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Pojazd` (
  `idPojazdu` INT NOT NULL AUTO_INCREMENT,
  `Wlasciciel` INT NOT NULL,
  `Typ` INT NOT NULL DEFAULT '2',
  `Marka` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Kolor` VARCHAR(45) NOT NULL,
  `Pojemnosc_Silnika` DECIMAL(3,1) NULL DEFAULT NULL,
  `Rodzaj_Silnika` ENUM('diesel', 'benzyna') NOT NULL,
  `Rok_Produkcji` DATE NOT NULL,
  `Data_Rejestracji` DATE NOT NULL,
  PRIMARY KEY (`idPojazdu`),
  INDEX `Typ` (`Typ` ASC) VISIBLE,
  INDEX `Wlasciciel` (`Wlasciciel` ASC) VISIBLE,
  CONSTRAINT `Pojazd_ibfk_1`
    FOREIGN KEY (`Typ`)
    REFERENCES `hryniewickij`.`Typ_Pojazdu` (`idTypu`),
  CONSTRAINT `Pojazd_ibfk_2`
    FOREIGN KEY (`Wlasciciel`)
    REFERENCES `hryniewickij`.`Klient` (`idKlienta`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Pracownik` (
  `idPracownika` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Pensja` DECIMAL(10,2) NULL DEFAULT NULL,
  `Data_Zatrudnienia` DATE NOT NULL,
  `Data_Urodzenia` DATE NOT NULL,
  PRIMARY KEY (`idPracownika`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Zlecenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Zlecenia` (
  `idZlecenia` INT NOT NULL AUTO_INCREMENT,
  `Zleceniodawca` INT NOT NULL,
  `Pracownik` INT NOT NULL,
  `Data_Przyjecia` DATE NOT NULL,
  PRIMARY KEY (`idZlecenia`),
  INDEX `Zleceniodawca` (`Zleceniodawca` ASC) VISIBLE,
  INDEX `Pracownik` (`Pracownik` ASC) VISIBLE,
  CONSTRAINT `Zlecenia_ibfk_1`
    FOREIGN KEY (`Zleceniodawca`)
    REFERENCES `hryniewickij`.`Klient` (`idKlienta`),
  CONSTRAINT `Zlecenia_ibfk_2`
    FOREIGN KEY (`Pracownik`)
    REFERENCES `hryniewickij`.`Pracownik` (`idPracownika`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Status` (
  `idStatusu` INT NOT NULL AUTO_INCREMENT,
  `Zlecenie` INT NOT NULL,
  `Status` ENUM('Otwarte', 'Zakonczone', 'Zawieszone') NOT NULL,
  `Roboczogodziny` INT NULL DEFAULT NULL,
  `Data_Zakonczenia` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idStatusu`),
  INDEX `Zlecenie` (`Zlecenie` ASC) VISIBLE,
  CONSTRAINT `Status_ibfk_1`
    FOREIGN KEY (`Zlecenie`)
    REFERENCES `hryniewickij`.`Zlecenia` (`idZlecenia`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hryniewickij`.`Uzyte_Elementy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hryniewickij`.`Uzyte_Elementy` (
  `NrZlecenia` INT NOT NULL,
  `Element` INT NOT NULL,
  INDEX `NrZlecenia` (`NrZlecenia` ASC) VISIBLE,
  INDEX `Element` (`Element` ASC) VISIBLE,
  CONSTRAINT `Uzyte_Elementy_ibfk_1`
    FOREIGN KEY (`NrZlecenia`)
    REFERENCES `hryniewickij`.`Zlecenia` (`idZlecenia`),
  CONSTRAINT `Uzyte_Elementy_ibfk_2`
    FOREIGN KEY (`Element`)
    REFERENCES `hryniewickij`.`Wyposazenie` (`idWyposazenia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `hryniewickij` ;

-- -----------------------------------------------------
-- function Otwarte_Zamowienia
-- -----------------------------------------------------

DELIMITER $$
USE `hryniewickij`$$
CREATE DEFINER=`hryniewickij`@`localhost` FUNCTION `Otwarte_Zamowienia`() RETURNS int
BEGIN
    DECLARE otwarte INT;
    SELECT COUNT(*) INTO @otwarte FROM Status where Status = 'Otwarte';
    RETURN @otwarte;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Zwolnij
-- -----------------------------------------------------

DELIMITER $$
USE `hryniewickij`$$
CREATE DEFINER=`hryniewickij`@`localhost` PROCEDURE `Zwolnij`(IN id int)
BEGIN
DELETE FROM Pracownik WHERE idPracownika = id;
END$$

DELIMITER ;
USE `hryniewickij`;

DELIMITER $$
USE `hryniewickij`$$
CREATE
DEFINER=`hryniewickij`@`localhost`
TRIGGER `hryniewickij`.`magazyn_update_0`
BEFORE UPDATE ON `hryniewickij`.`Magazyn`
FOR EACH ROW
BEGIN
  IF NEW.ilosc < 0
  THEN
    SET NEW.ilosc = 0;
  END IF;
END$$

USE `hryniewickij`$$
CREATE
DEFINER=`hryniewickij`@`localhost`
TRIGGER `hryniewickij`.`Najnizsza_Krajowa`
BEFORE INSERT ON `hryniewickij`.`Pracownik`
FOR EACH ROW
BEGIN
  IF NEW.Pensja < 2600
  THEN
    SET NEW.Pensja = 2600;
  END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
